### ISSUE TITLE
xGroup: Get-DscConfiguration fails

### ISSUE THREAD

**Issue by bozho** [dsccommunity/xPSDesiredStateConfiguration#353]
I'm working on a fairly complex DSC configuration which contains several partial configurations. One of them contains two xGroup resources.

After I publish and run the configuration (successfully), running Get-DscConfiguration fails with:
```
Get-DscConfiguration : GetConfiguration did not succeed.
At line:1 char:1
+ Get-DscConfiguration
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager) [Get
   -DscConfiguration], CimException
    + FullyQualifiedErrorId : MI RESULT 1,Get-DscConfiguration
```

DSC event log shows three error entries:
```
Job {5386BEF3-3C1A-11E7-80C3-3E1DBB675B2A} : 
Message Unable to cast object of type 'System.Management.Automation.PSObject' to type 'System.Object[]'. 
HResult -2147467262 
StackTrack    at System.Management.Automation.LanguagePrimitives.ConvertTo[T](Object valueToConvert)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.GetPSObjectArrayValue(CimType cimType, Object propertyValue)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.GetTargetResource(IntPtr resourceConfigurationInstanceHandle, IntPtr nonResourcePropetiesHandle, IntPtr metaConfigHandle, IntPtr regInstanceHandle, IStreamsHandler plugInStreamsHandler, IntPtr& outputInstanceHandle, IntPtr& errorInstanceHandle)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, IntPtr instance, IntPtr nonResourcePropeties, IntPtr metaConfig, IntPtr regInstance, IntPtr outputInstance, IntPtr extendedError)
```

```
Job {5386BEF3-3C1A-11E7-80C3-3E1DBB675B2A} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [xGroup]Elements_Instances and Source Info is ::48::3::xGroup. Error Message is NULL.
```

```
Job {5386BEF3-3C1A-11E7-80C3-3E1DBB675B2A} : 
MIResult: 1
Error Message: GetConfiguration did not succeed.
Message ID: MI RESULT 1
Error Category: 0
Error Code: 1
Error Type: MI
```

The error occurs when either one or both xGroup resources are present.

If I manually import MSFT_xGroupResource.psm1 in a powershell window and run Get-TargetResource, it runs fine.

I don't have a minimal example for now, but if I could get some guidance on debugging the configuration as it is now, I'd be more than happy to take a look.

OS: 
```
Windows Server 2012R2
```
$PSVersionTable:
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.36366
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
xPSDesiredStateConfiguration: 
```
6.4.0.0
```

**Comment by Chirishman** [comment]
I'm having the same problem with the 1.1 version of PSDesiredStateConfiguration which ships bundled with WMF 5.1

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
Message Unable to cast object of type 'System.String' to type 'System.Collections.IList'.
Parameter name: value 
HResult -2147024809 
StackTrack    at Microsoft.Management.Infrastructure.Internal.Data.CimPropertyOfInstance.set_Value(Object value)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.GetTargetResource(IntPtr resourceConfigurationInstanceHandle, IntPtr nonResourcePropetiesHandle, IntPtr metaConfigHandle, IntPtr regInstanceHandle, IStreamsHandler plugInStreamsHandler, IntPtr& outputInstanceHandle, IntPtr& errorInstanceHandle)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, IntPtr instance, IntPtr nonResourcePropeties, IntPtr metaConfig, IntPtr regInstance, IntPtr outputInstance, IntPtr extendedError)
```

```
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [xVMHyperV]TestVM1 and Source Info is C:\Users\fakename\Documents\WindowsPowerShell\Modules\DSCToolkit\ConfigPrimitives\ClientVM.ps1::77::7::xVMHyperV. Error Message is NULL.
```

**Comment by t3mi** [comment]
Faced the same issue myself when xGroup contains only one member. Changing next line in function Get-TargetResourceOnFullSKU
```$members = Get-MembersOnFullSKU -Group $group -PrincipalContextCache $principalContextCache `-Credential $Credential -Disposables $disposables```
to 
```[array] $members = Get-MembersOnFullSKU -Group $group -PrincipalContextCache $principalContextCache `
                -Credential $Credential -Disposables $disposables```
fixes the issue.
